[package]
name = "dbmigrator_core"
version = "0.4.3-alpha"
edition = "2021"

[dependencies]
regex = "1"
thiserror.workspace = true
walkdir = "2.4"
sha2 = "0.10"
version-compare = "0.2.0"

[dev-dependencies]
tempfile = "3"
